### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by BY-jk** [jaraco/path.py#107]
Would it be possible to add a file LICENSE with the MIT license (http://opensource.org/licenses/MIT) to the repositories root directory?
The setup.py states this module is licensed under MIT. However, it is good and common practice to repeat the concrete license text in a LICENSE file.

**Comment by jaraco** [comment]
I'd rather not. It feels like unnecessary duplication and ambiguity. What if the stated license conflicts with the in-place one? I'd rather just keep it simple and reference the license by name, especially for small packages like this.

Thanks for the suggestion, though.

**Comment by BY-jk** [comment]
I understand you concerns. However, your argument can be looked at from the user perspective. If you 'only' have the license stated in the setup.py meta data, how can you be sure that users understand what you mean by 'MIT'?
I think this is the reason why it is good practice (and recommended by github https://help.github.com/articles/open-source-licensing/#where-does-the-license-live-on-my-repository) to have the license text in the repo. After all, these license texts tend to change over time (just think of BSD).
Still, I am happy with your clarification that the MIT license is the currently valid license.
