### ISSUE TITLE
pkg_resources may be undefined when catching exception

### ISSUE THREAD

**Issue by takluyver** [jaraco/path.py#111]
This was reported on Python 2 on Arch, as jupyter/notebook#1320

[This code](https://github.com/jaraco/path.py/blob/9ee36737fb663cc739877c820ff376c861a81cdf/path.py#L121-L127) tries to catch an error from pkg_resources, but pkg_resources may not have successfully imported when it does.

```
Traceback (most recent call last):
...
File "/usr/lib/python2.7/site-packages/pickleshare.py",
line 41, in <module>
from path import path as Path
File "/usr/lib/python2.7/site-packages/path.py",
line 126, in <module>
except pkg_resources.DistributionNotFound:
NameError: name 'pkg_resources' is not defined
```

**Comment by Nodd** [comment]
I encountered the same problem. What's strange is that it's random, relaunching the exact same program may work or not.

**Comment by jaraco** [comment]
I'm not sure how to address the problem. Surely the exception trapping could be made more aggressive, and perhaps that makes sense. I wish I knew though what exception is being thrown in `import pkg_resources` that's not an ImportError. Also odd that the behavior is intermittent.

I guess trapping exceptions more aggressively is the best thing, but if you can, in an environment that's failing, determine how `import pkg_resources` is failing, and report back here, that would be appreciated.
