### ISSUE TITLE
Unnecessary performance penalties in .listdir()

### ISSUE THREAD

**Issue by nmaier** [jaraco/path.py#115]
I use path.py in various py3 applications that `.files()` or even `walkfiles()` a lot of directories and files... Thousands of  directories and hundreds of thousands of files.
The system has a slow CPU too (Atom SoC slow), so I noticed that a lot of time is spend within `.listdir` and/or `.walk*`, so I investigated.
1. PY3 is penalized by calling `_always_unicode` for each file, although PY3 guarantees unicode already. Therefore `_always_unicode`should only be called at all when `not PY3`.
2. empty (`None`) patterns aka the default will still try to do pattern matching in `listdir` by then defaulting `*` internally. This is aggravated by the `walk*` methods doing another round of pattern matching after that, but this time at least it's conditional on `pattern is not None`. Therefore pattern matching in `listdir` should onyl be carried out when the caller actually provided a pattern to match
3. `.fnmatch`, which is also used by `listdir`/`walk*`
   - always tries to get a `default_normcase` from `pattern` or the module. It should only do that when no `normcase` argument is provided.
   - always applies the `normcase` to the pattern too. In the case of `listdir`/`walk*` this leads to `normcase`ing the same pattern once per item. Therefore `list`/`walk` should prepare the pattern once and avoid the additional `normcase` calls.

One script I tested, with a hackishly modified path.py to address 1. and 2., has a runtime reduction of over a minute or about 37% with a hot file system cache. But seeing that my use case is "heavy" and my system is "light", YMMV

**Comment by jaraco** [comment]
Fixed in #120.
