### ISSUE TITLE
Documentation no longer hosted on PyPI

### ISSUE THREAD

**Issue by jaraco** [jaraco/path.py#118]
As PyPI is dropping support for documentation, I've removed the documentation from pythonhosted.org/path.py as the updated release process will not work with the old system and there's no replacement system... and I don't want stale docs on pythonhosted.org to confuse anybody.

What we need is someone to configure the docs to be hosted elsewhere, but I don't have the time to do that.

**Comment by rspeed** [comment]
I went ahead and [set it up on readthedocs](https://pathpy.readthedocs.io/en/latest/). I also recently [contributed a Docker docset](https://github.com/Kapeli/Dash-User-Contributions/tree/master/docsets/path.py).

**Comment by jaraco** [comment]
Awesome. Thanks @rspeed!

**Comment by rspeed** [comment]
Happy to help!

**Comment by rspeed** [comment]
Oh, and if you have an account on RTD let me know your username so I can add you as a maintainer.

**Comment by jaraco** [comment]
@rspeed: Great. My username is `jaraco`. Thanks.

**Comment by jaraco** [comment]
Turns out that RTD won't build the docs automatically unless one [configures a webhook](https://docs.readthedocs.io/en/latest/webhooks.html), so I've done that.

**Comment by rspeed** [comment]
I wasn't even aware that's as option. Though it certainly makes sense.
