### ISSUE TITLE
NameError: name 'basestring' is not defined

### ISSUE THREAD

**Issue by rcwchan** [jaraco/path.py#128]
Hi,

I receive the following error from a function calling `_radd_` from `path` in Python 3.6.1:

```
  File "/scratch/software/lib/python3.6/site-packages/path.py", line 111, in __radd__
    if isinstance(other, basestring):
NameError: name 'basestring' is not defined

```

After taking a look at the path.py source, it appears `basestring` is not imported from `past.builtins`--should that be the case?

Thanks!

**Comment by jaraco** [comment]
I'm fairly certain you have an old copy of path.py installed. If you look at the [latest code on line 111](https://github.com/jaraco/path.py/blob/master/path.py#L111), there's nothing there. Furthermore, in the latest version, `basestring` is [only ever mentioned on Python 2](https://github.com/jaraco/path.py/blob/master/path.py#L93).

Try to use `python3 -m pip install --upgrade path.py` and that should get you straightened out.
