### ISSUE TITLE
pip3.5 install SimpleHTTPServer Collecting http.server   Could not find a version that satisfies the requirement http.server (from versions: ) No matching distribution found for http.server

### ISSUE THREAD

**Issue by talktoshishir** [jaraco/path.py#131]
pip3.5 -V
pip 9.0.1 from /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (python 3.5)
Need some help here.
MAC oS X 10.11.6

**Comment by jaraco** [comment]
Your issue describes a misunderstanding with what pip does and its role installing packages. Please ask a question in StackOverflow describing what you're trying to do, what you expect to happen, and what's happening instead. You have most of that here, but the path.py project is not involved.

Good luck.
