### ISSUE TITLE
Don't use distutils at runtime

### ISSUE THREAD

**Issue by SnarkBoojum** [jaraco/path.py#141]
Hi,

the following patch has been proposed in Debian.
[avoid-distutils.diff.txt](https://github.com/jaraco/path.py/files/2269874/avoid-distutils.diff.txt)

It might be interesting upstream too.

**Comment by jaraco** [comment]
As you investigate, Try to devise a backward compatible patch. But if there’s a small facet of the behavior that’s difficult or messy to maintain, it may be acceptable to make a backward incompatible change.
