### ISSUE TITLE
Add tempdir as part of the public API?

### ISSUE THREAD

**Issue by SethMMorton** [jaraco/path.py#142]
The [`tempdir`](https://github.com/jaraco/path.py/blob/f63d25af52a09cfc535c3a29f47cbb99acc9ff0c/path.py#L1632) object is pretty useful, but it does not appear in the [API documentation](https://pathpy.readthedocs.io/en/latest/api.html).   I wonder if there a specific reason it is not advertised...  if not, I think it would be a very nice feature to add to the `path.py` toolbelt.

**Comment by SethMMorton** [comment]
Yeah, `TempDir` is better.

I think when `path.py` switched from `path.path` to `path.Path`, you did `path = Path` for a couple versions.  Perhaps this methodology should be used here? Probably only `TempDir` and not `tempdir` would need to be added to `__all__` and be advertised, correct?

I can submit a PR for this if you would like.

**Comment by jaraco** [comment]
That all sounds exactly right.
