### ISSUE TITLE
Add a Path.iglob method?

### ISSUE THREAD

**Issue by SethMMorton** [jaraco/path.py#143]
There is a [`Path.glob`](https://github.com/jaraco/path.py/blob/f63d25af52a09cfc535c3a29f47cbb99acc9ff0c/path.py#L743) method, but there have been times where I wished I could use the iterator version from [`glob.iglob`](https://docs.python.org/3/library/glob.html#glob.iglob) with `path.py`.  Would it be possible to add an `iglob` method to `Path`, or conversly add a flag to `Path.glob` that uses `glob.iglob` instead of `glob.glob` under the hood?

**Comment by SethMMorton** [comment]
If there is interest, I would be happy to submit a pull request for this.

**Comment by jaraco** [comment]
I recently learned that [iglob is not generally usable](https://bugs.python.org/issue1366311), so I'm sort-of disinclined to expose it.

That said, if Python still exposes it, path.py probably should also. Would you consider sending a PR?

**Comment by SethMMorton** [comment]
I can submit a PR, but I want to make sure that you actually want to expose it in light of the bug you referenced. It seems that it is only an issue when multithreading, but I do understand not wanting to pass on bugs to users.
