### ISSUE TITLE
Use of pkg_resources greatly adds to startup time

### ISSUE THREAD

**Issue by SethMMorton** [jaraco/path.py#146]
I would like to start by saying I genuinely love `path.py` and will continue using it no matter the outcome of filing this issue.  This is going to be yet another "`pkg_resources` is slow" issue... sorry.  Rather than provide new evidence to this, I will simply refer to pypa/setuptools#510 and the links/discussions therein.

Why do I think this is a big enough problem to file an issue? `path.py` is the type of module that could potentially be used in every script or command-line tool (since interacting with the filesystem is almost always unavoidable), so if a user/organization decides to use it as their primary filesystem abstraction then all of their scripts incur a startup penalty. This penalty is non-trivial - importing `path.py` makes command-line tool startup go from imperceptible to very noticeable where I work (we have many packages installed in `site-packages`). To solve this, I either have to

- Create a local fork of `path.py` that removes the call to `pkg_resources` that my organization can use (instead of the version on PyPI). Not desirable, since they will become quickly out-of-sync.
- Copy the `path.py` source file into the source code for the command-line tool and manually remove the call to `pkg_resources` (undesirable for all the reasons above).
- Use the following hack when importing `path.py`

```python
import sys
sys.modules['pkg_resources'] = None
import path
del sys.modules['pkg_resources']
```

None of these are desirable.

I fully understand why `path.py` is using `setuptools_scm` (and thus `pkg_resources`) - there should only be one source of "truth" for the version, and the VCS version is an excellent way to define truth. 
But perhaps there is another way?

- There is a tool [`bumpversion`](https://github.com/c4urself/bump2version) that can be used to control the version of a package, and it can be used to also create the tags in your VCS. This could be used as the source for version "truth", and can remove the reliance on `setuptools_scm`.
- There may be ways to make `__version__` a module property so that `pkg_resources` need only be imported if `__version__` is explicitly requested. [This seems rather hacky, though](https://stackoverflow.com/q/880530/1399279).

My purpose in posting this is not to complain, but hopefully to start a constructive discussion that will result in `path.py` imports being as fast as something like [`six`](https://github.com/benjaminp/six). No matter *how* this is resolved, I think it would be a big win for `path.py` if import time is reduced.

**Comment by jaraco** [comment]
Another possible solution - wait for [importlib_metadata](https://gitlab.com/python-devs/importlib_metadata/) to land and we can use that instead.

**Comment by SethMMorton** [comment]
Haha, so looks like you have already been working on this problem!!  This looks like the "correct" solution.  Do you know when `importlib_metadata` will be released?  Will it wait for Python 3.8, or will it show up on PyPI sooner?

**Comment by SethMMorton** [comment]
Well, now I'm embarrassed... [it is on PyPI already](https://pypi.org/project/importlib-metadata/) (I was in transit when I made the above post).

So far, I believe that `path.py` has tried to avoid any third-party dependencies (well, except `setuptools_scm` and `pkg_resources`).  Is there any hesitation on depending on this module?

**Comment by jaraco** [comment]
> will it show up on PyPI sooner?

Yes. I'm hoping to make the 0.1 release prior to the PyPA summit at the end of October (and maybe sooner).

> Is there any hesitation on depending on this module?

Good point. Yes, the dependency will be optional, the same way `pkg_resources` is currently optional.
