### ISSUE TITLE
path.__version__ == 'unknown' on Python 3.4 and 3.5

### ISSUE THREAD

**Issue by userzimmermann** [jaraco/path.py#150]
```python
>>> import path      
>>> path
<module 'path' from 'c:\\tools\\miniconda3\\envs\\moon\\lib\\site-packages\\path.py'>                                            
>>> path.__version__                                             
'unknown'                                                              
>>> from pkg_resources import get_distribution                                                      
>>> get_distribution('path.py')
path.py 11.2.0 (c:\tools\miniconda3\envs\moon\lib\site-packages)
```

Same on Windows and Linux. With Python 2.7 and 3.6+ `path.__version__` is correct

**Comment by jaraco** [comment]
Thanks for reporting this. In the latest release, I switched to using importlib_metadata instead of pkg_resources, which is still very new.

Can you confirm you have importlib_metadata installed? If you don't have importlib_metadata installed, this is the expected behavior.

**Comment by userzimmermann** [comment]
@jaraco: Thanks for the quick response! Found the actual root cause: https://gitlab.com/python-devs/importlib_metadata/merge_requests/12

**Comment by userzimmermann** [comment]
@jaraco: And under the local operating system of my choice, there is even a 2nd root cause ;) https://gitlab.com/python-devs/importlib_metadata/merge_requests/13
