### ISSUE TITLE
TestPerformance.test_import_time fails on 32bit arch

### ISSUE THREAD

**Issue by scarabeusiv** [jaraco/path.py#159]
When running the test on 32bit arch I get following error:

[   79s] >       assert duration < limit
[   79s] E       assert datetime.timedelta(microseconds=184000) < datetime.timedelta(microseconds=100000)

I suppose the test shoudl be skipped on 32bit platform with acceptance of its slowness :)

**Comment by rickysarraf** [comment]
Oh!! We hit the same issue on arm 32 bits.

```
[  361s]         cmd = [
[  361s]             sys.executable,
[  361s]             '-m', 'timeit',
[  361s]             '-n', '1',
[  361s]             '-r', '1',
[  361s]             'import path',
[  361s]         ]
[  361s]         res = subprocess.check_output(cmd, universal_newlines=True)
[  361s]         dur = re.search(r'(\d+) msec per loop', res).group(1)
[  361s]         limit = datetime.timedelta(milliseconds=100)
[  361s]         duration = datetime.timedelta(milliseconds=int(dur))
[  361s] >       assert duration < limit
[  361s] E       assert datetime.timedelta(microseconds=101000) < datetime.timedelta(microseconds=100000)
[  361s] 
[  361s] test_path.py:260: AssertionError
```

**Comment by jaraco** [comment]
Yeah, that test really is brittle. I chose 100ms arbitrarily, but really I'm just trying to ensure that the performance stays reasonable. Perhaps I should mark that test as xfail. It will xpass on many platforms and xfail on others. Better would be if the test could somehow account for the speed of the host. Another option is we could disable/delete the test.

**Comment by jaraco** [comment]
I really wouldn't expect the word size to be a factor in startup performance. I had a thought - maybe the issue isn't the word size of the machine, but instead some other environmental factor (other startup costs in the interpreter in the environment where you're testing).

In the bugfix/159-import-time branch, I've added a commit which passes `-S` to the python interpreter when testing the import time, thinking that this might make the test more performant on these systems. Would either of you care to give this branch a run in your environments?
