### ISSUE TITLE
Path "freezeability"

### ISSUE THREAD

**Issue by njalerikson** [jaraco/path.py#161]
I've been monkey patching Python's pathlib to introduce a freezeability logic to paths. I have been pleasantly surprised by path.py's attempt at addressing what I consider glaring weaknesses of pathlib (while also eliminating certain over-complications), so I am seeing if there is interest in incorporating this freezeability logic here.

I agree that at its core, freezeability is a convenience to `abspath` and `relpath`.

With freezability I can define a path (absolute or relative), freeze said path (which then internally absolutes said path). With a frozen path I can then move around on my system but the path continues to work correctly. A frozen path has two views, relative and absolute. A Path also has control over which view to default to when stringifying. Once a Path is frozen, it can also be unfrozen which then un-absolutes a path.

```
p1 = Path("../foo")
p1.relative  # ../foo
p1.absolute  # ValueError
str(p1)  # ../foo

# freeze a path
p1.freeze()
p1.relative  # ../foo
p1.absolute  # /bar/baz/foo
str(p1)  # ../foo

# default to stringifying as absolute
p1.showrelative = False
p1.relative  # ../foo
p1.absolute  # /bar/baz/foo
str(p1)  # /bar/baz/foo
```

I've found that using freeze logic significantly simplifies and streamlines many of the confusions of dealing with lexical path operations (like `Path("foo").parent.parent`) since there is an internal path on which the actual operations occur, but then the user gets to see and deal with nice relative paths if possible.

If this is of interest I will get started on a PR.

**Comment by njalerikson** [comment]
The inheritance and reliance on `str` make this near impossible to implement without reengineering a significant portion of **path.py**. As such I will close this given that I do not expect any such efforts to be of interest.

**Comment by jaraco** [comment]
I don't see why you couldn't do this easily with a subclass of Path:

```
class Frozen(Path):
    def __init__(self, val):
        super().__init__(val)
        self.base = Path.getcwd()

    @property
    def absolute(self):
        return (self.base / self).abspath()
```

Then, if you want a frozen path from a regular path, just `fp = Frozen(regular)`.

Note, I haven't attempted this, but I would be interested to know, since you've found it impossible, why it's impossible.

**Comment by njalerikson** [comment]
Hehe, I suspected that saying "impossible" was going to come back and bite me.

I see how you're thinking about this.

The way I had been thinking about this was from the perspective of a path object itself needing to be mutable and while it's possible to make a subclass of str be mutable, doing so quickly became very...unnatural and hacky.

Your solution would enable a frozen path but doesn't necessarily allow for a path to become unfrozen again (a less important concept that I was trying to implement in parallel). Simply unsetting the base wouldn't properly unfreeze the path based on my understanding of unfreeze, where the unfrozen path is the same as the frozen path's relative path. This wouldn't be impossible to do, it would just require additional reverse logic to generate a different base that provides the proper relative path.

In my use case I do also think that to properly address cases where CWD has changed the implementation of `_next_class` would also need to change in order to properly carry the correct CWD from instance to instance. But this could also become a burden in other cases so I'm starting to view this as application specific as opposed to library level.

```python
class classinstmethod(object):
    def __init__(self, func):
        self.func = func

    def __get__(self, instance, owner):
        return functools.partial(self.func, owner, instance)


class Path(text_type):
    def __new__(cls, *paths):
        # for backwards compatibility
        if None in paths:
            raise TypeError("Invalid initial value for path: None")

        if paths:
            path = cls.module.join(*map(text_type, paths))
        else:
            path = os.curdir

        return super(Path, cls).__new__(cls, path)

    ...


class Frozen(Path):
    def __new__(cls, *paths, **kwargs):
        self = super(Frozen, cls).__new__(cls, *paths)

        if "base" in kwargs:
            self.base = Path(kwargs.pop("base"))
        else:
            self.base = Path.getcwd()

        if kwargs:
            raise TypeError(kwargs)

        return self

    @classinstmethod
    def _next_class(cls, self, val, **kwargs):
        if self is not None:
            kwargs.setdefault("base", self.base)
        return cls(val, **kwargs)

    @property
    def absolute(self):
        return (self.base / self).expand().abspath()

    @property
    def relative(self):
        return self.absolute.relpath()
```

```python
path = Frozen("../foo")
path.relative  # .
path.absolute  # /bar/baz/foo

os.chdir("../..")  # /bar

path2 = path / "qux"
path2.relative  # baz/foo/qux
path2.absolute  # /bar/baz/foo/qux

# versus what would occur if base isn't passed along
path3 = Frozen.joinpath(str(path), "qux")
path3.relative  # ../foo/qux
path3.absolute  # /foo/qux
```

**Comment by jaraco** [comment]
Maybe this works:

```
class Frozen(Path):
    def __init__(self, val, base=None):
        super().__init__(val)
        self.base = base or Path.getcwd()

    @property
    def absolute(self):
        return (self.base / self).abspath()

    @ClassProperty
    @classmethod
    def _next_class(cls):
        return functools.partial(cls, base=self.base)
```
