### ISSUE TITLE
Path().rmdir_p() errors on non-empty folder

### ISSUE THREAD

**Issue by mathause** [jaraco/path.py#171]
When I try to delete a non-empty folder with `rmdir_p` it raises an error.

``` python
import path
from path import Path

tmpdir = path.tempdir()
self = None # I directly created a test case for test_path.py

def test_rmdir_p_sub_sub_dir(self, tmpdir):
    """
    A non-empty folder should not raise an exception.
    """
    d = Path(tmpdir)
    sub = d / 'subfolder'
    sub.mkdir()
    subsub = sub / 'subfolder'
    subsub.mkdir()

    sub.rmdir_p()

test_rmdir_p_sub_sub_dir(self, tmpdir)
```

This raises the following error:

``` python
~/path.py/path/__init__.py in translate()
   1459             _, e, _ = sys.exc_info()
   1460             if e.errno == errno.ENOTEMPTY:
-> 1461                 e.__class__ = DirectoryNotEmpty
   1462             raise
   1463

TypeError: __class__ assignment only supported for heap types or ModuleType subclasses
```

After replacing [Line 1461](https://github.com/jaraco/path.py/blob/master/path/__init__.py#L1461) with `pass` it raises an `OSError` (according to the docstring it should not raise, or?).

Usage question - should `rmdir_p()` delete a non-empty folder? Or should it silently fail? To delete non-empty folders should `rmtree` be used?

python 3.7.0
``` python
path.__version__
>>> '12.0.2.dev2+g91a5c22'
```

**Comment by mathause** [comment]
In `10.3.1` this fails silently, so I assume this is the intended behavior.

**Comment by mathause** [comment]
ping @jaraco

**Comment by jaraco** [comment]
The docstring for `rmdir_p` says:

> Like `rmdir`, but does not raise an exception if the directory is not empty or does not exist.

The way I read that is it should not delete a non-empty folder; it should silently fail and one should use rmtree for that situation.

**Comment by jaraco** [comment]
Thanks for providing the test. I've added it verbatim in 628db41.

**Comment by jaraco** [comment]
(replaced with bc602bf for proper attribution)

**Comment by mathause** [comment]
Great, thank you!
