### ISSUE TITLE
Namespacing for file operations

### ISSUE THREAD

**Issue by sametmax** [jaraco/path.py#58]
I gave some thoughts to the discussion we had here : https://github.com/jaraco/path.py/issues/26

The `status` proposal gave me an idea. We could actually generalize since the `path` class is becomming big, and maybe it would be beneficial to start separating responsabilities in the lib.

Some actions are clearly not related to a path, but to a file such as :

- calculating md5
- gettings stats
- getting text from file
- getting mimetype
etc

Also, the fact the class `path` is supposed to deal with only a path make it difficult to add handy features that are file related without making it a strange melting pot.

This is why I'm suggesting we make a namespace dedicated to file operations. We could simply name it `file`, and it would be used this way :

```
>>> p = path('/etc/fstab')
>>> p.file.file_operation()
```

This would remove from the main namespace a lot of methods, making shell exploration easier.  It would also be the occasion to remove duplicates, matching the Zen of Python "there should be only one way to do it". Currently we keep several names to match the `os.path` API and aliases for compat reasons. While this is supposed to help, with the current size of the lib, it's becoming less and less convenient to instinctly find the proper method without several trials or looking at the source code.

Enventually, it allows us to make the API more modern and adopt a fluid syntaxe :

```
statvfs() -> p.file.statvfs()
atime and getatime() -> p.file.atime
mtime and getmtime() -> p.file.mtime
ctime and getctime() -> p.file.ctime
utime -> p.file.utime
write_text() -> p.file.write(data)
write_bytes() -> p.file.write(data, 'b')
text() -> p.file.text
?() -> p.file.bytes
lstat() -> p.file.lstat()
read_hash() -> p.file.hash()
read_hexhash() -> p.file.hash().hexdigest()
read_md5() -> p.file.md5()
chunks() -> p.file.chunks()
getsize() -> p.file.size
stat() -> p.file.stat()
inplace() -> p.file.inplace()
```

`file` could also be a callable that opens the file and returns a file like object :

```
for line in p.file():
    # do stuff
```

The `file()` callable would accept all the parameters `codec.open` accept, a bit like what `path.open` does, but with `encoding` as well (set to 'utf8' as default like in Python 3).

However, it would not returns a stdlib file like object, but rather a proxy (or a monkeypatched deepcopy for perfs) with all the same attributes except an additional `.path` returning the original `path` object used to open the file :

```
>>> p.file().path is p
True
```

Last time you shared with me your concern about being backward incompatible, so i'm suggesting this to be added in an experimental branch in which we can play with what can be the future of path.py. Including all rejected features that would have made it backward incompatible, just to see where it leads us.

This branch can be used for future features such as asynchronous file system manipulations, name wrangling, advanced permission checks or anything that is not acceptable to put in the good old path.py.

path.py is now very stable and feature complete, and I don't think it's going to move much. We can safely support this version ad vitam and consider freezing it in the comming years while trying new things on the experimental branch.

Another benefit of the experimental branch is we can drop 2.7 support and focus on Python 3, making the codebase a bit smaller. path.py as is will always be supported for 2.7 and 3 and always be available. We don't really need to touch it.

**Comment by jaraco** [comment]
Although these ideas have their merits, we seem to have stalled on a suitable interface. I'm closing for now, but feel free to revive as interest allows.
