### ISSUE TITLE
Pip installation either broken or non-obvious

### ISSUE THREAD

**Issue by holdenweb** [jaraco/path.py#79]
The documentation says that `path` "may be installed using `setuptools`, `distribute`, or `pip`" but only gives an example of easy_install.

Which left me a little upset when I tried to install the package.

    airhead:Projects sholden$ pip install path
    Downloading/unpacking path
      Could not find any downloads that satisfy the requirement path
    No distributions at all found for path
    Storing complete log in /Users/sholden/.pip/pip.log

Pip installation should just work. Maybe the notes could mention that since path is a modue rther than a package it should be installed with

    pip install path.py

**Comment by jaraco** [comment]
The project name of `path.py` is a poor name. Very few Python packages use a name with a period in them, unless they're a namespace package. I'd like to rename the project to `path`, but that name is held by the Path Language. So the legacy lives on and we do the best with what we have.
