### ISSUE TITLE
io.open is not a file object

### ISSUE THREAD

**Issue by Nodd** [jaraco/path.py#83]
Since e708619170fab2112f4bacf5693b842302d47531, Path.open uses io.open which return a stream, which apparentely is not compatible with a File object, which is what is expected for example in  [numpy.ndarray.tofile](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.tofile.html).

Maybe the fault is in numpy, but this is still a compatibility problem with previous path.py versions.

**Comment by Nodd** [comment]
Actually there is an opened bug about this in numpy : https://github.com/numpy/numpy/issues/2230.

**Comment by jaraco** [comment]
Thanks for reporting the issue and linking the downstream ticket.

This change was introduced in the 7.0 release, for which the version number and the changelog both communicate clearly the possibility of incompatibility. The result is still a file-like object, which is suitable in nearly every case (and is in fact unavoidable on Python 3), so there's nothing more to be done here.
