### ISSUE TITLE
chown does not show up in docs

### ISSUE THREAD

**Issue by mbruzek** [jaraco/path.py#93]
I can not find the chown method in path.py docs at https://pythonhosted.org/path.py/api.html

It looks like the docs do not recognize the chown method when creating documentation.  
  
Looking at the code it is due to the if statement on line 1136.  
https://github.com/jaraco/path.py/blob/master/path.py#L1136

Is there any way we can make the generation of docs include this function?

**Comment by jaraco** [comment]
I suspect the issue is that the implementation varies based on the os/platform where the documentation is generated. In this case, the docs were generated on Windows where os.chown didn't exist. I think you're right that the implementation should be consistent across platforms, even if it raises an error on unsupported platforms.

**Comment by mbruzek** [comment]
Hello @jaraco,
Thanks for the response.  I am embarrassed to say that this problem has struck me twice (months apart).  The first place I go when using path.py is the API documentation.  Because I use path.py so infrequently I forgot that I found this in the code.  

I will make a pull request to fix this as you have described.  

Thanks again for the response.

  - Matt

**Comment by satoon101** [comment]
There are other methods that suffer from the same issue.  All of those methods should probably receive the same treatment, as well.

**Comment by mbruzek** [comment]
@satoon101 I was not aware of the other issues.  I would be happy to make individual pull requests to fix these so each one can be judged on its own merit.

I haven't got any feedback on PR #94 yet.  Don't know if that is normal, or means something else like it is not a good implementation.

**Comment by jaraco** [comment]
No feedback just means no one has had the time to review. I will get to it in time. Thanks for your patience and understanding.

**Comment by jaraco** [comment]
Do please feel free to open another issue to capture irregularity of interface for non-present methods.
