### ISSUE TITLE
Define __rdiv__ and __rtruediv__

### ISSUE THREAD

**Issue by sametmax** [jaraco/path.py#97]
Currently you can do this: 

    Path('foo') / 'bar'

But not this:

    'foo' / Path('bar')

This can be solved with \_\_rdiv__ and \_\_rtruediv__:

https://github.com/sametmax/path.py/commit/5649e5edcd4864b020fccfcb7f7cb67a96b30880

Should I PR ?

**Comment by jaraco** [comment]
You should have commit privileges. I say just commit the changes. Don't forget to update the changelog.

**Comment by sametmax** [comment]
Fixed by https://github.com/jaraco/path.py/commit/5649e5edcd4864b020fccfcb7f7cb67a96b30880.
